import type { ItemContent } from "../schemas";

/**
 * Curios: no use effect — their entire job is to be kept. Includes the
 * prize-wheel pools' curiosities (../daily/prize-wheel.ts references them
 * by slug). Non-stackable entries are per-copy instances; provenance
 * policies beyond NONE record item history.
 */
export const curiosityItems = [
  {
    slug: "unremarkable-acorn",
    name: "Unremarkable Acorn",
    description: "An acorn of no particular consequence. It disagrees.",
    type: null,
    category: "curios",
    tags: ["foraged", "woodland"],
    price: 5n,
    rarity: "COMMON",
    artKey: "unremarkable-acorn",
  },
  {
    slug: "river-glass-pebble",
    name: "River-Glass Pebble",
    description:
      "Smoothed by years of patient water. Looks best held up to the light.",
    type: null,
    category: "curios",
    tags: ["river", "keepsake"],
    price: 14n,
    rarity: "UNCOMMON",
    artKey: "river-glass-pebble",
  },
  {
    slug: "pressed-fern-frond",
    name: "Pressed Fern Frond",
    description: "A fern flattened between the pages of somebody's ledger.",
    type: null,
    category: "curios",
    tags: ["foraged", "keepsake"],
    price: 9n,
    rarity: "COMMON",
    artKey: "pressed-fern-frond",
  },
  {
    slug: "echo-shell",
    name: "Echo Shell",
    description:
      "Hold it to your ear and hear the river. Hold it further away and hear nothing, which is also the river.",
    type: null,
    category: "curios",
    tags: ["river", "keepsake"],
    price: 220n,
    rarity: "RARE",
    artKey: "echo-shell",
  },
  {
    slug: "sunshower-vial",
    name: "Sunshower Vial",
    description:
      "Rain that fell while the sun was out, bottled before it could decide which it was.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 90n,
    rarity: "UNCOMMON",
    artKey: "sunshower-vial",
  },
  {
    slug: "gilded-acorn",
    name: "Gilded Acorn",
    description:
      "Somebody gilded an acorn. Nobody has explained why, and at this price nobody asks.",
    type: null,
    category: "curios",
    tags: ["woodland", "keepsake"],
    price: 1200n,
    rarity: "ULTRA_RARE",
    artKey: "gilded-acorn",
  },
  {
    slug: "fernlight-lantern",
    name: "Fernlight Lantern",
    description:
      "Glows a soft green without fuel, flame, or explanation. Each one is numbered by the maker.",
    type: null,
    category: "curios",
    tags: ["woodland", "keepsake"],
    price: 400n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "ORIGINAL_SOURCE",
    artKey: "fernlight-lantern",
  },
  {
    slug: "grovewardens-compass",
    name: "Grovewarden's Compass",
    description:
      "Points somewhere important. Previous owners have disagreed, at length, about where.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 2500n,
    rarity: "ULTRA_RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "grovewardens-compass",
  },
  {
    slug: "wanderers-first-map",
    name: "Wanderer's First Map",
    description:
      "The map every wanderer starts with. Slightly wrong in ways you will come to treasure.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 5n,
    rarity: "COMMON",
    tradeable: false,
    artKey: "wanderers-first-map",
  },

  // ---- Prize-wheel curiosities (Brassbell Pavilion) ----
  {
    slug: "dewdrop-vial",
    name: "Dewdrop Vial",
    description: "A stoppered vial of morning dew, collected before it noticed.",
    type: null,
    category: "curios",
    tags: ["keepsake", "foraged"],
    price: 20n,
    rarity: "COMMON",
    artKey: "dewdrop-vial",
  },
  {
    slug: "patchwork-ribbon",
    name: "Patchwork Ribbon",
    description: "Seven fabrics, one ribbon, zero matching opinions.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 15n,
    rarity: "COMMON",
    artKey: "patchwork-ribbon",
  },
  {
    slug: "mossy-brass-button",
    name: "Mossy Brass Button",
    description: "Lost from a very fine coat, found by very patient moss.",
    type: null,
    category: "curios",
    tags: ["keepsake", "woodland"],
    price: 18n,
    rarity: "COMMON",
    artKey: "mossy-brass-button",
  },
  {
    slug: "painted-river-pebble",
    name: "Painted River Pebble",
    description: "Painted by hand, smoothed by river, judged by no one.",
    type: null,
    category: "curios",
    tags: ["keepsake", "river"],
    price: 12n,
    rarity: "COMMON",
    artKey: "painted-river-pebble",
  },
  {
    slug: "tiny-copper-bell",
    name: "Tiny Copper Bell",
    description: "Rings a note so small it is mostly a suggestion.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 22n,
    rarity: "COMMON",
    artKey: "tiny-copper-bell",
  },
  {
    slug: "woven-fern-bookmark",
    name: "Woven Fern Bookmark",
    description: "Keeps your place. Withholds all spoilers.",
    type: null,
    category: "curios",
    tags: ["keepsake", "woodland"],
    price: 16n,
    rarity: "COMMON",
    artKey: "woven-fern-bookmark",
  },
  {
    slug: "starroot-brooch",
    name: "Starroot Brooch",
    description: "Carved from a root that grew stubbornly toward the night sky.",
    type: null,
    category: "curios",
    tags: ["keepsake", "woodland"],
    price: 600n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "starroot-brooch",
  },
  {
    slug: "moonglass-teacup",
    name: "Moonglass Teacup",
    description: "Holds tea, moonlight, and exactly one polite secret.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 550n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "moonglass-teacup",
  },
  {
    slug: "whispering-compass",
    name: "Whispering Compass",
    description: "Points wherever you were already going, and murmurs approval.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 700n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "whispering-compass",
  },
  {
    slug: "glasswing-music-box",
    name: "Glasswing Music Box",
    description: "Plays a tune remembered from a dream nobody admits to.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 800n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "glasswing-music-box",
  },
  {
    slug: "crown-of-quiet-lanterns",
    name: "Crown of Quiet Lanterns",
    description: "Six tiny lanterns that light only when nobody is looking.",
    type: null,
    category: "curios",
    tags: ["keepsake"],
    price: 900n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "crown-of-quiet-lanterns",
  },
  {
    slug: "silvercloud-keepsake",
    name: "Silvercloud Keepsake",
    description:
      "A pocket of captured drizzle from a cloud with sentimental value.",
    type: null,
    category: "curios",
    tags: ["keepsake", "river"],
    price: 650n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "silvercloud-keepsake",
  },

  // ---- Saltmere: lost property, found on the flats ----
  {
    slug: "one-left-boot",
    name: "One Left Boot",
    description:
      "Excellent condition, entirely alone. The Wrackline has another one. They have never been introduced.",
    type: null,
    category: "curios",
    tags: ["salvaged"],
    price: 6n,
    rarity: "COMMON",
    artKey: "one-left-boot",
  },
  {
    slug: "waterlogged-luggage-tag",
    name: "Waterlogged Luggage Tag",
    description:
      "The name has gone. The destination has gone. The string is in perfect condition.",
    type: null,
    category: "curios",
    tags: ["salvaged"],
    price: 7n,
    rarity: "COMMON",
    artKey: "waterlogged-luggage-tag",
  },
  {
    slug: "chipped-enamel-mug",
    name: "Chipped Enamel Mug",
    description:
      "White, blue rim, one chip. There are two hundred of these on the flats and every one of them is somebody's.",
    type: null,
    category: "curios",
    tags: ["salvaged"],
    price: 8n,
    rarity: "COMMON",
    artKey: "chipped-enamel-mug",
  },
  {
    slug: "salt-rakers-tally",
    name: "Salt Raker's Tally",
    description:
      "A stick notched once for every rack of salt dried. It runs out of notches well before the season runs out of racks.",
    type: null,
    category: "curios",
    tags: ["salvaged"],
    price: 12n,
    rarity: "COMMON",
    artKey: "salt-rakers-tally",
  },
  {
    slug: "bent-brass-hinge",
    name: "Bent Brass Hinge",
    description:
      "Bent in a direction hinges are not supposed to go. Somebody's door has been sticking for years.",
    type: null,
    category: "curios",
    tags: ["salvaged"],
    price: 18n,
    rarity: "UNCOMMON",
    artKey: "bent-brass-hinge",
  },

  // ---- Saltmere: recovered things ----
  {
    slug: "tide-worn-tin",
    name: "Tide-Worn Tin",
    description:
      "A small tin rubbed featureless by sand. Whatever it advertised has been out of business for a while.",
    type: null,
    category: "curios",
    tags: ["salvaged", "tidal"],
    price: 7n,
    rarity: "COMMON",
    artKey: "tide-worn-tin",
  },
  {
    slug: "beacon-lamp-glass",
    name: "Beacon Lamp Glass",
    description:
      "A pane from the beacon's old lamp, replaced years ago for reasons nobody wrote down. It still throws a warm ring on the wall.",
    type: null,
    category: "curios",
    tags: ["salvaged", "keepsake"],
    price: 85n,
    rarity: "UNCOMMON",
    artKey: "beacon-lamp-glass",
  },
  {
    slug: "netted-glass-float",
    name: "Netted Glass Float",
    description:
      "A green glass sphere in a rope net, built to hold a net up and to be lost. It succeeded at both.",
    type: null,
    category: "curios",
    tags: ["salvaged", "tidal"],
    price: 380n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "ORIGINAL_SOURCE",
    artKey: "netted-glass-float",
  },
  {
    slug: "salvagers-tide-clock",
    name: "Salvager's Tide Clock",
    description:
      "One hand, no numbers, and a confident opinion about when the water leaves. It has been right often enough to keep.",
    type: null,
    category: "curios",
    tags: ["salvaged", "keepsake"],
    price: 520n,
    rarity: "RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "salvagers-tide-clock",
  },
  {
    slug: "unclaimed-lot-key",
    name: "Unclaimed Lot Key",
    description:
      "Tagged, numbered, and never collected. The counter stopped waiting a long time ago. The key has not.",
    type: null,
    category: "curios",
    tags: ["salvaged", "keepsake"],
    price: 1800n,
    rarity: "ULTRA_RARE",
    stackable: false,
    provenancePolicy: "FULL_HISTORY",
    artKey: "unclaimed-lot-key",
  },
] satisfies readonly ItemContent[];
