import type { ItemContent } from "../schemas";

/**
 * Edible items. FOOD items feed pets (hungerRestore). The Hearth and
 * Ladle daily meal pool draws from the common foods below
 * (../daily/community-meal.ts references these by slug).
 */
export const foodItems = [
  {
    slug: "sunberry-cluster",
    name: "Sunberry Cluster",
    description: "A handful of sweet golden berries picked at first light.",
    type: "FOOD",
    category: "food",
    tags: ["sweet", "foraged"],
    price: 12n,
    rarity: "COMMON",
    hungerRestore: 15,
    artKey: "sunberry-cluster",
  },
  {
    slug: "honey-oat-loaf",
    name: "Honey Oat Loaf",
    description: "A dense little loaf baked with grove honey and rolled oats.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet"],
    price: 25n,
    rarity: "COMMON",
    hungerRestore: 30,
    artKey: "honey-oat-loaf",
  },
  {
    slug: "crispleaf-salad",
    name: "Crispleaf Salad",
    description: "Crunchy greens tossed with dewdrops and seed sprinkles.",
    type: "FOOD",
    category: "food",
    tags: ["foraged"],
    price: 18n,
    rarity: "COMMON",
    hungerRestore: 20,
    artKey: "crispleaf-salad",
  },
  {
    slug: "river-melon-slice",
    name: "River Melon Slice",
    description: "A juicy wedge of melon chilled in a cold stream.",
    type: "FOOD",
    category: "food",
    tags: ["river", "sweet"],
    price: 20n,
    rarity: "COMMON",
    hungerRestore: 25,
    artKey: "river-melon-slice",
  },
  {
    slug: "acorn-tea",
    name: "Acorn Tea",
    description:
      "Steeped until it tastes reassuringly of autumn. Serves one, slowly.",
    type: "FOOD",
    category: "food",
    tags: ["foraged", "woodland"],
    price: 8n,
    rarity: "COMMON",
    hungerRestore: 10,
    artKey: "acorn-tea",
  },
  {
    slug: "riverweed-crisps",
    name: "Riverweed Crisps",
    description: "Salted, dried, and louder than any snack needs to be.",
    type: "FOOD",
    category: "food",
    tags: ["river"],
    price: 14n,
    rarity: "COMMON",
    hungerRestore: 15,
    artKey: "riverweed-crisps",
  },
  {
    slug: "toasted-nutcake",
    name: "Toasted Nutcake",
    description: "A hearty cake of ground nuts, toasted until golden.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "woodland"],
    price: 35n,
    rarity: "UNCOMMON",
    hungerRestore: 40,
    artKey: "toasted-nutcake",
  },
  {
    slug: "mossberry-jam",
    name: "Mossberry Jam",
    description:
      "The recipe is a village secret, in the sense that the whole village knows it.",
    type: "FOOD",
    category: "food",
    tags: ["sweet", "foraged"],
    price: 55n,
    rarity: "UNCOMMON",
    hungerRestore: 35,
    artKey: "mossberry-jam",
  },
  {
    slug: "drizzle-cake",
    name: "Drizzle Cake",
    description:
      "Baked only on mornings when the rain is exactly the right kind.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet"],
    price: 150n,
    rarity: "RARE",
    hungerRestore: 60,
    artKey: "drizzle-cake",
  },

  // ---- Community meal dishes (Hearth and Ladle) ----
  {
    slug: "honey-oat-biscuit",
    name: "Honey-Oat Biscuit",
    description: "Firm enough for travel and, regrettably, conversation.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet"],
    price: 10n,
    rarity: "COMMON",
    hungerRestore: 15,
    artKey: "honey-oat-biscuit",
  },
  {
    slug: "mushroom-hand-pie",
    name: "Mushroom Hand Pie",
    description: "The mushroom declined to comment.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "woodland"],
    price: 16n,
    rarity: "COMMON",
    hungerRestore: 25,
    artKey: "mushroom-hand-pie",
  },
  {
    slug: "berry-jam-toast",
    name: "Berry Jam Toast",
    description: "Mostly jam. The toast is serving a structural role.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet"],
    price: 12n,
    rarity: "COMMON",
    hungerRestore: 18,
    artKey: "berry-jam-toast",
  },
  {
    slug: "apple-clover-tart",
    name: "Apple-Clover Tart",
    description: "Four leaves were considered excessive.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "foraged"],
    price: 14n,
    rarity: "COMMON",
    hungerRestore: 20,
    artKey: "apple-clover-tart",
  },
  {
    slug: "warm-root-stew",
    name: "Warm Root Stew",
    description: "Its ingredients are best described as subterranean.",
    type: "FOOD",
    category: "food",
    tags: ["foraged", "woodland"],
    price: 18n,
    rarity: "COMMON",
    hungerRestore: 30,
    artKey: "warm-root-stew",
  },
  {
    slug: "cloudberry-muffin",
    name: "Cloudberry Muffin",
    description: "Contains berries. Cloud content remains disputed.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet"],
    price: 13n,
    rarity: "COMMON",
    hungerRestore: 18,
    artKey: "cloudberry-muffin",
  },
  {
    slug: "herb-flecked-bread",
    name: "Herb-Flecked Bread",
    description: "Every fleck has been accounted for.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "foraged"],
    price: 11n,
    rarity: "COMMON",
    hungerRestore: 16,
    artKey: "herb-flecked-bread",
  },
  {
    slug: "roasted-mooncarrot",
    name: "Roasted Mooncarrot",
    description: "Not from the moon. Marketing prevailed.",
    type: "FOOD",
    category: "food",
    tags: ["foraged"],
    price: 9n,
    rarity: "COMMON",
    hungerRestore: 14,
    artKey: "roasted-mooncarrot",
  },
  {
    slug: "pear-and-thyme-scone",
    name: "Pear and Thyme Scone",
    description: "Available today, and also thyme.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet"],
    price: 13n,
    rarity: "COMMON",
    hungerRestore: 18,
    artKey: "pear-and-thyme-scone",
  },
  {
    slug: "cinnamon-moss-cake",
    name: "Cinnamon Moss Cake",
    description: "The moss is decorative. Probably.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "sweet", "woodland"],
    price: 15n,
    rarity: "COMMON",
    hungerRestore: 22,
    artKey: "cinnamon-moss-cake",
  },

  // ---- Saltmere: food that keeps ----
  {
    slug: "bittergreen-broth",
    name: "Bittergreen Broth",
    description:
      "Warm, green, and bracing. Nobody claims to like it; everybody orders it in bad weather.",
    type: "FOOD",
    category: "food",
    tags: ["salted", "foraged"],
    price: 8n,
    rarity: "COMMON",
    hungerRestore: 12,
    artKey: "bittergreen-broth",
  },
  {
    slug: "hardtack-square",
    name: "Hardtack Square",
    description:
      "Bread built to outlast the journey and, frequently, the traveller's patience. Best softened in something warm.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "preserved"],
    price: 9n,
    rarity: "COMMON",
    hungerRestore: 14,
    artKey: "hardtack-square",
  },
  {
    slug: "salt-crust-roll",
    name: "Salt-Crust Roll",
    description:
      "A crust of salt keeps the middle soft for a week. Both halves are edible; only one of them is enjoyable.",
    type: "FOOD",
    category: "food",
    tags: ["baked", "salted"],
    price: 12n,
    rarity: "COMMON",
    hungerRestore: 16,
    artKey: "salt-crust-roll",
  },
  {
    slug: "honeyed-shoreberries",
    name: "Honeyed Shoreberries",
    description:
      "Small orange berries from the scrub above the waterline, boiled with honey to talk them out of being sour. Mostly successful.",
    type: "FOOD",
    category: "food",
    tags: ["sweet", "tidal"],
    price: 15n,
    rarity: "COMMON",
    hungerRestore: 20,
    artKey: "honeyed-shoreberries",
  },
  {
    slug: "brine-pickled-roots",
    name: "Brine-Pickled Roots",
    description:
      "Roots kept in brine since a season nobody agrees on. Still crunchy, which some find suspicious.",
    type: "FOOD",
    category: "food",
    tags: ["salted", "preserved"],
    price: 34n,
    rarity: "UNCOMMON",
    hungerRestore: 38,
    artKey: "brine-pickled-roots",
  },
  {
    slug: "storm-preserve",
    name: "Storm Preserve",
    description:
      "Made only from fruit knocked down by weather, which limits production and encourages optimism about weather.",
    type: "FOOD",
    category: "food",
    tags: ["sweet", "preserved"],
    price: 160n,
    rarity: "RARE",
    hungerRestore: 60,
    artKey: "storm-preserve",
  },
] satisfies readonly ItemContent[];
