/**
 * npm run art:items — turns the sourced icon map into the placeholder item
 * artwork the game ships.
 *
 * Run it against a checkout of https://github.com/game-icons/icons:
 *
 *   git clone --depth 1 https://github.com/game-icons/icons /tmp/game-icons
 *   npm run art:items -- /tmp/game-icons
 *
 * It writes three things and owns all three, so none of them can drift:
 *
 *   public/art/items/<artKey>.svg        one silhouette per item
 *   src/components/art/item-icons.ts     the art keys that have one
 *   docs/art-credits.md                  the attribution CC BY 3.0 requires
 *
 * Why a checkout rather than a fetch: the collection is the upstream
 * source of truth, and pinning to whatever it says today — rather than
 * whatever a URL returns during a future build — is what keeps a
 * reproducible build reproducible. Nothing in the app ever reaches out to
 * game-icons.net at runtime; these are our files once they land here.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ICON_AUTHORS, ITEM_ICON_MAP } from "../src/lib/art-credits";

const OUT_DIR = "public/art/items";
const KEYS_MODULE = "src/components/art/item-icons.ts";
const CREDITS = "docs/art-credits.md";

const source = process.argv[2];
if (!source) {
  console.error(
    "Usage: npm run art:items -- <path to a game-icons/icons checkout>",
  );
  process.exit(1);
}

/**
 * Pulls the drawn shape out of a collection icon.
 *
 * Every icon in the collection is a black background rectangle followed by
 * the white foreground, because the collection's own downloads offer
 * colour combinations. We want the shape alone: the app renders it as a
 * CSS mask and takes its colour from the palette, so a background
 * rectangle would mask the entire square and paint a solid block.
 *
 * The background is always the first path and always the full-viewport
 * rectangle, so it is matched by shape rather than by position — a change
 * upstream that reorders them should drop out here, not turn every item
 * into a coloured square.
 */
const BACKGROUND = /<path d="M0 0h512v512H0z"\s*\/>/;
const PATHS = /<path\b[^>]*\/>|<path\b[^>]*>[\s\S]*?<\/path>/g;

function shapeOf(svg: string, id: string): string {
  const withoutBackground = svg.replace(BACKGROUND, "");
  if (withoutBackground === svg) {
    throw new Error(
      `${id}: no background rectangle found — the upstream icon format changed, so the extraction below is no longer safe`,
    );
  }
  const paths = withoutBackground.match(PATHS);
  if (!paths || paths.length === 0) {
    throw new Error(`${id}: no drawn paths after removing the background`);
  }
  // Fill is irrelevant to a mask — only alpha matters — but stating it
  // keeps the file sensible when opened on its own, and keeps any stray
  // `fill="#fff"` from rendering white-on-white in a file viewer.
  return paths
    .map((path) => path.replace(/\s*fill="[^"]*"/g, "").replace("<path", '<path fill="#000"'))
    .join("");
}

const entries = Object.entries(ITEM_ICON_MAP).sort(([a], [b]) => a.localeCompare(b));
const seenIcons = new Map<string, string[]>();
const usedAuthors = new Set<string>();

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

let bytes = 0;
for (const [artKey, icon] of entries) {
  const [author, name] = icon.split("/");
  if (!author || !name) {
    throw new Error(`${artKey}: "${icon}" is not <author>/<icon>`);
  }
  if (!ICON_AUTHORS[author]) {
    throw new Error(
      `${artKey}: no credit line for contributor "${author}" — add one to ICON_AUTHORS before using their work`,
    );
  }
  usedAuthors.add(author);

  const file = join(source, author, `${name}.svg`);
  let raw: string;
  try {
    raw = readFileSync(file, "utf8");
  } catch {
    throw new Error(`${artKey}: ${icon} not found at ${file}`);
  }

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">${shapeOf(raw, artKey)}</svg>\n`;
  writeFileSync(join(OUT_DIR, `${artKey}.svg`), svg);
  bytes += svg.length;

  seenIcons.set(icon, [...(seenIcons.get(icon) ?? []), artKey]);
}

// Two items sharing a silhouette is the failure the old placeholder had:
// the satchel is scanned by shape first, and two identical shapes make the
// list unreadable however correct each one is on its own.
const shared = [...seenIcons.entries()].filter(([, keys]) => keys.length > 1);
if (shared.length > 0) {
  throw new Error(
    `icons reused across items:\n${shared
      .map(([icon, keys]) => `  ${icon} → ${keys.join(", ")}`)
      .join("\n")}`,
  );
}

writeFileSync(
  KEYS_MODULE,
  `// Generated by scripts/build-item-icons.ts — do not edit by hand.
//
// Which items have a sourced silhouette in public/art/items. Items absent
// here fall back to their category shape in ItemArt, so new content is
// never blocked on artwork and a missing file can never render as a solid
// coloured square.
export const ITEM_ICON_KEYS: ReadonlySet<string> = new Set([
${entries.map(([artKey]) => `  ${JSON.stringify(artKey)},`).join("\n")}
]);
`,
);

const credited = [...usedAuthors].sort().map((author) => {
  const { name, url } = ICON_AUTHORS[author] as { name: string; url: string | null };
  return url ? `- [${name}](${url})` : `- ${name}`;
});

writeFileSync(
  CREDITS,
  `<!-- Generated by scripts/build-item-icons.ts — do not edit by hand. -->

# Art credits

## Item placeholder icons

The item silhouettes under \`public/art/items/\` are derived from the
[game-icons.net](https://game-icons.net) collection
([source](https://github.com/game-icons/icons)), used under the
[Creative Commons Attribution 3.0 licence](https://creativecommons.org/licenses/by/3.0/).

They are modified: each icon's background rectangle is removed and the
remaining shape is rendered as a CSS mask so it takes its colour from the
game's palette tokens.

Icons by:

${credited.join("\n")}

These are placeholders. They stand in for original commissioned artwork
and carry no part of the world's identity (docs/art-direction.md).

### Per-item

| Item art key | Icon |
| --- | --- |
${entries.map(([artKey, icon]) => `| \`${artKey}\` | \`${icon}\` |`).join("\n")}
`,
);

const stale = readdirSync(OUT_DIR).length;
console.log(
  `art:items — ${entries.length} icons, ${stale} files, ${(bytes / 1024).toFixed(0)} KB total`,
);
console.log(`  ${OUT_DIR}\n  ${KEYS_MODULE}\n  ${CREDITS}`);
